spring.datasource.url=jdbc:postgresql://localhost:5432/telegramBot
spring.datasource.username=myUser
spring.datasource.password=123
telegram.bot.token=7955356861:AAGQ-8phBlhqNbPu-2s4cDu1tN8yHMR4SWM
spring.jpa.hibernate.ddl-auto= validate
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
logging.file.name=telegram-bot.log