-- liquibase formatted sql

-- changeset RedSunRnD:1
CREATE TABLE IF NOT EXISTS notification_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    date_time TIMESTAMP NOT NULL,
    is_done BOOLEAN,
    text_message VARCHAR(255) NOT NULL
    );